### PR TITLE
Circumvent invalid test names caused by import errors

### PR DESCRIPTION
**Pull request by gergelypolonkai**
Possible fix for #1

Signed-off-by: Gergely Polonkai <gergely@polonkai.eu>

### CODE REVIEW

**Comment by stevejalim** [comment]
Makes sense - thanks @gergelypolonkai. 

Any chance you can add a test, to protect against regressions if, say, `unittest` changes its exception path or name?

**Comment by gergelypolonkai** [comment]
How about this?

    if name.startswith 'unittest.loader.':
        name = '.'.join(name.split('.')[3:])

This won’t work if the exception gets higher or deeper in the module hierarchy, though…

**Comment by gergelypolonkai** [comment]
We can be pretty sure the `unittest.` part will be the same forever(ish), but the remaining parts of the path seems almost undetectable to me. But if you have any ideas, I’m willing to implement it.

**Comment by gergelypolonkai** [comment]
I didn’t intend to close this, as the solution didn’t get merged. Or did it?

**Comment by stevejalim** [comment]
I don't think this has been merged yet, no - I can't reopen as it wasn't my PR

**Comment by gergelypolonkai** [comment]
Me neither, as it says “There are no new commits on the gergelypolonkai:master branch”. Reopened it as #23.

**Pull request closed without merging**
