### PR TITLE
Circumvent invalid test names caused by import errors

### PR DESCRIPTION
**Pull request by gergelypolonkai**

### CODE REVIEW

**Comment by stevejalim** [comment]
Thanks, @gergelypolonkai! 

As mentioned before, a test for the regression-warning test in the custom loader would be nice, if you've still got it around.

**Comment by gergelypolonkai** [comment]
You mean the case if `unittest` decides to put the `ImportError` exception to a different path? Or a specific warning I don’t see in my logs? (If the latter, I’d be thankful for a log excerpt!)

**Comment by stevejalim** [comment]
The former, I reckon - but it’s a small thing

--
Steve Jalim

Technical Director

steve@somefantastic.co.uk // 07740 819849 // 020 3239 3292

www.somefantastic.co.uk // @SomeFantastic <http://twitter.com/SomeFantastic>

Some Fantastic Limited, 51 Somers Park Avenue, Malvern, Worcestershire WR14
1SE, UK.
Registered in England, No. 06194144 // VAT reg: GB 118051641

**Comment by gergelypolonkai** [comment]
I had a proposal in #18 for that. Or we can look for `ModuleImportFailure` in the test case name, but if the exception gets renamed, we’re doomed again… Maybe we can run a test discovery (:warning: overhead alert! :warning:) and compare test names to the ones in the rerun log, but that sounds much worse than relying on `unittest`’s API.

Speaking of which, I find it pretty unlikely this exception will be renamed or moved. `unittest` API seems to be stable for a bunch of major releases now, so I don’t see the point.

**Comment by stevejalim** [comment]
Sure - let’s go without it. If the code moves beneath it, we'll know soon enough :)

@Geekfish - you like?

**Comment by Geekfish** [comment]
Looks like a quick win 👍

**Comment by gergelypolonkai** [comment]
Just to note, this PR ill solve #1 (just to add a link between the original issue and the PR).

**Pull request merged**
